main.o: Q1-1_brute_force_knapsack.cpp Q1-2_greedy_algorithm.cpp Q1-3_dynamic_programming_knapsack.cpp Q2_dijkstra.cpp
	g++ -o Q1-1_brute_force_knapsack.out -std=c++11 Q1-1_brute_force_knapsack.cpp
	g++ -o Q1-2_greedy_algorithm.out -std=c++11 Q1-2_greedy_algorithm.cpp
	g++ -o Q1-3_dynamic_programming_knapsack.out -std=c++11 Q1-3_dynamic_programming_knapsack.cpp
	g++ -o Q2_dijkstra.out -std=c++11 Q2_dijkstra.cpp
	
clean:
	rm -f *.out